name: Generate Git Bonsai

on:
  schedule:
    - cron: "30 11 * * *"
  workflow_dispatch:

jobs:
  grow-bonsai:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Update Bonsai Asset
        uses: egorthinks/git-bonsai@v1
